# Generated by Django 5.2.13 on 2026-04-11 15:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('risk_band', models.CharField(max_length=32)),
                ('components', models.JSONField(default=dict)),
                ('engine_version', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_result', to='applications.application')),
            ],
            options={
                'db_table': 'score_result',
            },
        ),
    ]
