# Generated by Django 5.2.13 on 2026-04-11 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(choices=[('approved', 'Approved'), ('manual_review', 'Manual review'), ('declined', 'Declined')], max_length=32)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('risk_band', models.CharField(blank=True, default='', max_length=32)),
                ('reason_summary', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('pipeline', 'Pipeline'), ('override', 'Override')], default='pipeline', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='applications.application')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_overrides', to=settings.AUTH_USER_MODEL)),
                ('previous_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseding_decisions', to='decisions.decision')),
            ],
            options={
                'db_table': 'decision',
                'ordering': ['-created_at'],
            },
        ),
    ]
