# Generated by Django 5.2.13 on 2026-04-11 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('condition', models.JSONField(default=dict)),
                ('outcome', models.CharField(choices=[('approved', 'Approved'), ('manual_review', 'Manual review'), ('declined', 'Declined')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_rule',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
