# Generated by Django 5.2.13 on 2026-04-11 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_reference', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('manual_review', 'Manual review'), ('approved', 'Approved'), ('declined', 'Declined'), ('failed', 'Failed')], db_index=True, default='queued', max_length=32)),
                ('raw_payload', models.JSONField()),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('principal_kind', models.CharField(choices=[('user', 'User'), ('api_key', 'API key')], max_length=16)),
                ('principal_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feature_snapshot',
            },
        ),
    ]
